<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\situs;

class situsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        situs::insert([
            [
                "situs_code" => "dingdongtogel",
                "name" => "Dingdongtogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/dingdong_togel/desktop",
                "url_desktop_prod" => "https://dingdongtogel176.com",
                "url_mobile_dev" => "/situs/dingdong_togel/m",
                "url_mobile_prod" => "https://dingdongtogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "fiatogel",
                "name" => "Fiatogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/fia_togel/desktop",
                "url_desktop_prod" => "https://fiatogel176.com/",
                "url_mobile_dev" => "/situs/fia_togel/m",
                "url_mobile_prod" => "https://fiatogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "gengtogel",
                "name" => "Gengtogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/geng_togel/desktop",
                "url_desktop_prod" => "https://gengtogel176.com/",
                "url_mobile_dev" => "/situs/geng_togel/mobile",
                "url_mobile_prod" => "https://gengtogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "hometogel",
                "name" => "Hometogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/home_togel/desktop",
                "url_desktop_prod" => "https://hometogel176.com/",
                "url_mobile_dev" => "/situs/home_togel/mobile",
                "url_mobile_prod" => "https://hometogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "indratogel",
                "name" => "Indratogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/indra_togel/desktop",
                "url_desktop_prod" => "https://indratogel176.com/",
                "url_mobile_dev" => "/situs/indra_togel/mobile",
                "url_mobile_prod" => "https://indratogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "jonitogel",
                "name" => "Jonitogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/joni_togel/desktop",
                "url_desktop_prod" => "https://jonitogel176.com/",
                "url_mobile_dev" => "/situs/joni_togel/mobile",
                "url_mobile_prod" => "https://jonitogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "lunatogel",
                "name" => "Lunatogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/luna_togel/desktop",
                "url_desktop_prod" => "https://lunatogel176.com/",
                "url_mobile_dev" => "/situs/luna_togel/m",
                "url_mobile_prod" => "https://lunatogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "mariatogel",
                "name" => "Mariatogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/maria_togel/desktop",
                "url_desktop_prod" => "https://mariatogel176.com/",
                "url_mobile_dev" => "/situs/maria_togel/m",
                "url_mobile_prod" => "https://mariatogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "oppatogel",
                "name" => "Oppatogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/oppa_toto/desktop",
                "url_desktop_prod" => "https://oppatoto176.com/",
                "url_mobile_dev" => "/situs/oppa_toto/mobile",
                "url_mobile_prod" => "https://oppatoto176.com/m/",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "patihtoto",
                "name" => "Patihtogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/patih_toto/desktop",
                "url_desktop_prod" => "https://patihtoto176.com/",
                "url_mobile_dev" => "/situs/patih_toto/mobile",
                "url_mobile_prod" => "https://patihtoto176.com/m/",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "protogel",
                "name" => "Protogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/pro_togel/desktop",
                "url_desktop_prod" => "https://protogel176.com/",
                "url_mobile_dev" => "/situs/pro_togel/mobile",
                "url_mobile_prod" => "https://protogel176.com/m/",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "pwvip4d",
                "name" => "Pwvip4d",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/pwvip4d/desktop",
                "url_desktop_prod" => "https://pwvip4d176.com/",
                "url_mobile_dev" => "/situs/pwvip4d/mobile",
                "url_mobile_prod" => "https://pwvip4d176.com/m/",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "togelon",
                "name" => "Togelon",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/togel_on/desktop",
                "url_desktop_prod" => "https://togelon176.com/",
                "url_mobile_dev" => "/situs/togel_on/m",
                "url_mobile_prod" => "https://togelon176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "togelup",
                "name" => "Togelup",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/togel_up/desktop",
                "url_desktop_prod" => "https://togelup176.com/",
                "url_mobile_dev" => "/situs/togel_up/mobile",
                "url_mobile_prod" => "https://togelup176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "udintogel",
                "name" => "Udintogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/udin_togel/desktop",
                "url_desktop_prod" => "https://udintogel176.com",
                "url_mobile_dev" => "/situs/udin_togel/mobile",
                "url_mobile_prod" => "https://udintogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "yoktogel",
                "name" => "Yoktogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/yok_togel/desktop",
                "url_desktop_prod" => "https://yoktogel176.net/",
                "url_mobile_dev" => "/situs/yok_togel/m",
                "url_mobile_prod" => "https://yoktogel176.net/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "yowestogel",
                "name" => "Yowestogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/yowes_togel/desktop",
                "url_desktop_prod" => "https://yowestogel176.com/",
                "url_mobile_dev" => "/situs/yowes_togel/m",
                "url_mobile_prod" => "https://yowestogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "ziatogel",
                "name" => "Ziatogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/zia_togel/desktop",
                "url_desktop_prod" => "https://ziatogel176.com/",
                "url_mobile_dev" => "/situs/zia_togel/m",
                "url_mobile_prod" => "https://ziatogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "danatogel",
                "name" => "Danatogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/dana_toto/desktop",
                "url_desktop_prod" => "https://danatoto176.com/",
                "url_mobile_dev" => "/situs/dana_toto/m",
                "url_mobile_prod" => "https://danatoto176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "nanastogel",
                "name" => "Nanastogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/nanas_toto/desktop",
                "url_desktop_prod" => "https://nanastoto176.com/",
                "url_mobile_dev" => "/situs/nanas_toto/m",
                "url_mobile_prod" => "https://nanastoto176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "linetogel",
                "name" => "Linetogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/line_togel/desktop",
                "url_desktop_prod" => "https://linetogel176.com/",
                "url_mobile_dev" => "/situs/line_togel/m",
                "url_mobile_prod" => "https://linetogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "partaitogel",
                "name" => "Partaitogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/partai_togel/desktop",
                "url_desktop_prod" => "https://partaitogel176.com/",
                "url_mobile_dev" => "/situs/partai_togel/m",
                "url_mobile_prod" => "https://partaitogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "goltogel",
                "name" => "Goltogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/gol_togel/desktop",
                "url_desktop_prod" => "https://goltogel176.com/",
                "url_mobile_dev" => "/situs/gol_togel/m",
                "url_mobile_prod" => "https://goltogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "situstoto",
                "name" => "Situstoto",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/situs_toto/desktop",
                "url_desktop_prod" => "https://situstoto176.com/",
                "url_mobile_dev" => "/situs/situs_toto/m",
                "url_mobile_prod" => "https://situstoto176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
