<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\situs;

class situsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        situs::insert([
            [
                "name" => "Dingdong Togel",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Fia Togel",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Geng Togel",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Home Togel",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Indra Togel",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Joni Togel",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Luna Togel",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Maria Togel",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Oppa Toto",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Patih Toto",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Puli Toto",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Proto Toto",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Pw4 VIP",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Togel On",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Togel Up",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Udin Togel",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Yok Togel",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Yowes Togel",
                "status_desktop" => false,
                "status_mobile" => false,
                "url_desktop_dev" => "",
                "url_desktop_prod" => "",
                "url_mobile_dev" => "",
                "url_mobile_prod" => "",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "Zia Togel",
                "status_desktop" => 1,
                "status_mobile" => 1,
                "url_desktop_dev" => "http://127.0.0.1:8000/zia_togel_desktop",
                "url_desktop_prod" => "https://ziatogel176.com/",
                "url_mobile_dev" => "http://127.0.0.1:8000/zia_togel_mobile",
                "url_mobile_prod" => "https://ziatogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
