<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\situs;

class situsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        situs::insert([
            [
                "situs_code" => "dingdongtogel",
                "name" => "Dingdongtogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/dingdongtogel/desktop",
                "url_desktop_prod" => "https://dingdongtogel176.com",
                "url_mobile_dev" => "/situs/dingdongtogel/m",
                "url_mobile_prod" => "https://dingdongtogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "fiatogel",
                "name" => "Fiatogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/fiatogel/desktop",
                "url_desktop_prod" => "https://fiatogel176.com/",
                "url_mobile_dev" => "/situs/fiatogel/m",
                "url_mobile_prod" => "https://fiatogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "gengtogel",
                "name" => "Gengtogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/gengtogel/desktop",
                "url_desktop_prod" => "https://gengtogel176.com/",
                "url_mobile_dev" => "/situs/gengtogel/mobile",
                "url_mobile_prod" => "https://gengtogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "hometogel",
                "name" => "Hometogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/hometogel/desktop",
                "url_desktop_prod" => "https://hometogel176.com/",
                "url_mobile_dev" => "/situs/hometogel/mobile",
                "url_mobile_prod" => "https://hometogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "indratogel",
                "name" => "Indratogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/indratogel/desktop",
                "url_desktop_prod" => "https://indratogel176.com/",
                "url_mobile_dev" => "/situs/indratogel/mobile",
                "url_mobile_prod" => "https://indratogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "jonitogel",
                "name" => "Jonitogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/jonitogel/desktop",
                "url_desktop_prod" => "https://jonitogel176.com/",
                "url_mobile_dev" => "/situs/jonitogel/mobile",
                "url_mobile_prod" => "https://jonitogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "lunatogel",
                "name" => "Lunatogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/lunatogel/desktop",
                "url_desktop_prod" => "https://lunatogel176.com/",
                "url_mobile_dev" => "/situs/lunatogel/m",
                "url_mobile_prod" => "https://lunatogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "mariatogel",
                "name" => "Mariatogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/mariatogel/desktop",
                "url_desktop_prod" => "https://mariatogel176.com/",
                "url_mobile_dev" => "/situs/mariatogel/m",
                "url_mobile_prod" => "https://mariatogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "oppatogel",
                "name" => "Oppatogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/oppatogel/desktop",
                "url_desktop_prod" => "https://oppatoto176.com/",
                "url_mobile_dev" => "/situs/oppatogel/mobile",
                "url_mobile_prod" => "https://oppatoto176.com/m/",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "patihtoto",
                "name" => "Patihtogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/patihtogel/desktop",
                "url_desktop_prod" => "https://patihtoto176.com/",
                "url_mobile_dev" => "/situs/patihtogel/mobile",
                "url_mobile_prod" => "https://patihtoto176.com/m/",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "protogel",
                "name" => "Protogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/protogel/desktop",
                "url_desktop_prod" => "https://protogel176.com/",
                "url_mobile_dev" => "/situs/protogel/mobile",
                "url_mobile_prod" => "https://protogel176.com/m/",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "pwvip4d",
                "name" => "Pwvip4d",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/pwvip4d/desktop",
                "url_desktop_prod" => "https://pwvip4d176.com/",
                "url_mobile_dev" => "/situs/pwvip4d/mobile",
                "url_mobile_prod" => "https://pwvip4d176.com/m/",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "togelon",
                "name" => "Togelon",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/togelon/desktop",
                "url_desktop_prod" => "https://togelon176.com/",
                "url_mobile_dev" => "/situs/togelon/m",
                "url_mobile_prod" => "https://togelon176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "togelup",
                "name" => "Togelup",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/togelup/desktop",
                "url_desktop_prod" => "https://togelup176.com/",
                "url_mobile_dev" => "/situs/togelup/mobile",
                "url_mobile_prod" => "https://togelup176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "udintogel",
                "name" => "Udintogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/udintogel/desktop",
                "url_desktop_prod" => "https://udintogel176.com",
                "url_mobile_dev" => "/situs/udintogel/mobile",
                "url_mobile_prod" => "https://udintogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "yoktogel",
                "name" => "Yoktogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/yoktogel/desktop",
                "url_desktop_prod" => "https://yoktogel176.net/",
                "url_mobile_dev" => "/situs/yoktogel/m",
                "url_mobile_prod" => "https://yoktogel176.net/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "yowestogel",
                "name" => "Yowestogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/yowestogel/desktop",
                "url_desktop_prod" => "https://yowestogel176.com/",
                "url_mobile_dev" => "/situs/yowestogel/m",
                "url_mobile_prod" => "https://yowestogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "ziatogel",
                "name" => "Ziatogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/ziatogel/desktop",
                "url_desktop_prod" => "https://ziatogel176.com/",
                "url_mobile_dev" => "/situs/ziatogel/m",
                "url_mobile_prod" => "https://ziatogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "danatogel",
                "name" => "Danatogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/danatogel/desktop",
                "url_desktop_prod" => "https://danatoto176.com/",
                "url_mobile_dev" => "/situs/danatogel/m",
                "url_mobile_prod" => "https://danatoto176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "nanastogel",
                "name" => "Nanastogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/nanastogel/desktop",
                "url_desktop_prod" => "https://nanastoto176.com/",
                "url_mobile_dev" => "/situs/nanastogel/m",
                "url_mobile_prod" => "https://nanastoto176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "linetogel",
                "name" => "Linetogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/linetogel/desktop",
                "url_desktop_prod" => "https://linetogel176.com/",
                "url_mobile_dev" => "/situs/linetogel/m",
                "url_mobile_prod" => "https://linetogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "partaitogel",
                "name" => "Partaitogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/partaitogel/desktop",
                "url_desktop_prod" => "https://partaitogel176.com/",
                "url_mobile_dev" => "/situs/partaitogel/m",
                "url_mobile_prod" => "https://partaitogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "goltogel",
                "name" => "Goltogel",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/goltogel/desktop",
                "url_desktop_prod" => "https://goltogel176.com/",
                "url_mobile_dev" => "/situs/goltogel/m",
                "url_mobile_prod" => "https://goltogel176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "situs_code" => "situstoto",
                "name" => "Situstoto",
                "status_desktop" => true,
                "status_mobile" => true,
                "url_desktop_dev" => "/situs/situstogel/desktop",
                "url_desktop_prod" => "https://situstoto176.com/",
                "url_mobile_dev" => "/situs/situstogel/m",
                "url_mobile_prod" => "https://situstoto176.com/m",
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
